import {
  BalloonModels,
  ConstructionAreas,
  ConstructionPhases,
  EnvelopeTypes,
  GasTypes,
  RecoverySystems,
} from "./types";

export const mockBalloons = [
  {
    id: "111",
    model: BalloonModels.Microballoon,
    constructionLocation: "123",
    cameraPayload: 1,
    trackingPayloadId: 2,
    constructionArea: ConstructionAreas.Bay_1,
    constructionPhase: ConstructionPhases.Packaging,
    envelopeType: EnvelopeTypes.Chloroprene,
    gasType: GasTypes.Helium,
    recoverySystem: RecoverySystems.Parachute,
  },
  {
    id: "222",
    model: BalloonModels.Microballoon,
    constructionLocation: "123",
    cameraPayload: 1,
    trackingPayloadId: 2,
    constructionArea: ConstructionAreas.Bay_2,
    constructionPhase: ConstructionPhases.PayloadIntegration,
    envelopeType: EnvelopeTypes.Latex,
    gasType: GasTypes.Hydrogen,
    recoverySystem: RecoverySystems.Parachute,
  },
  {
    id: "333",
    model: BalloonModels.Microballoon,
    constructionLocation: "123",
    cameraPayload: 1,
    trackingPayloadId: 2,
    constructionArea: ConstructionAreas.Bay_3,
    constructionPhase: ConstructionPhases.Packaging,
    envelopeType: EnvelopeTypes.Chloroprene,
    gasType: GasTypes.Helium,
    recoverySystem: RecoverySystems.SoftLanding,
  },
  {
    id: "444",
    model: BalloonModels.Transosonde,
    constructionLocation: "456",
    cameraPayload: 1,
    trackingPayloadId: 2,
    constructionArea: ConstructionAreas.Bay_1,
    constructionPhase: ConstructionPhases.EnvelopeMolding,
    envelopeType: EnvelopeTypes.Chloroprene,
    gasType: GasTypes.Hydrogen,
    recoverySystem: RecoverySystems.SoftLanding,
  },
  {
    id: "555",
    model: BalloonModels.Transosonde,
    constructionLocation: "456",
    cameraPayload: 1,
    trackingPayloadId: 2,
    constructionArea: ConstructionAreas.Bay_1,
    constructionPhase: ConstructionPhases.EnvelopeMolding,
    envelopeType: EnvelopeTypes.Chloroprene,
    gasType: GasTypes.Hydrogen,
    recoverySystem: RecoverySystems.SoftLanding,
  },
];
